/// Flutter icons IconApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconApp
///      fonts:
///       - asset: fonts/IconApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconApp {
  IconApp._();

  static const _kFontFam = 'IconApp';
  static const String? _kFontPkg = null;

  static const IconData iconApp = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
