/// Flutter icons IconFasilitas
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconFasilitas
///      fonts:
///       - asset: fonts/IconFasilitas.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconFasilitas {
  IconFasilitas._();

  static const _kFontFam = 'IconFasilitas';
  static const String? _kFontPkg = null;

  static const IconData masjid = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parking = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData penginapan = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toilet = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
